### ISSUE TITLE
how to use the edl loss when distilate?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [Cogito2012/DEAR#2]

**Comment by Cogito2012** [comment]
@zimenglan-sysu-512 I guess you are referring to the way of knowledge distillation (KD) when using EDL loss?

This is interesting. In EDL, the expectation of classification probability is reformulated as `\alpha / S` rather than softmax normalization, similar to the temperature scaling technique in KD, probably you can set a scaling factor for the Dirichlet strength, e.g., `\lambda S`, such that the Dirichlet is more centralized, which further produces more centralized samplings of multinomial probabilities. However, it should be careful about how the uncertainty is changing correspondingly (should be linearly scaled intuitively.)

Correct me if I misunderstood your question.
