### ISSUE TITLE
Computation of HSIC 

### ISSUE THREAD

**Issue by Pirazh** [Cogito2012/DEAR#4]
Hi, 

Thank you for your great work. I was going through the code and notice that [here](https://github.com/Cogito2012/DEAR/blob/97d0e8f191da0f20dcc9721280af48171dabef5e/mmaction/models/heads/debias_head.py#L137) you would like to make only the diagonal elements zero which is consistent with the original paper "Feature Selection via Dependence Maximization". However, `torch.diag` function which you used here, has different behaviors when the input is vector or a matrix. Since here it is taking a matrix as the input, its output is a vector containing diagonal elements and `kernel_XX - torch.diag(kernel_XX)` subtracts the diagonal elements from all the elements in the corresponding column. The fix would be to change this line to `kernel_XX - torch.diag(torch.diag(kernel_XX))`. Could you please confirm this?

**Comment by Cogito2012** [comment]
@Pirazh Thanks for pointing out this issue. You are right after I referred to the `torch.diag` definition from [pytorch doc](https://pytorch.org/docs/stable/generated/torch.diag.html). Since my HSIC omputation was adapted from the ICML'21 work ReBias where their HSIC code is [here](https://github.com/clovaai/rebias/blob/79d1d1d892412a5e3b07fbea8b776461bed0e096/criterions/hsic.py#L86), I believe they have exactly the same issue as this one. I'll update the code later.
